eHealth/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('administrador.urls')),
    url(r'^medico/', include('medico.urls')),
    url(r'^paciente/', include('paciente.urls')),
    ]

medico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve
from medico.views import *


urlpatterns = [
    url(
        r'^perfil-medico/(?P<id>\w+)$',
        PerfilMedico.as_view(),
        name='perfil_medico'
    ),
    url(
        r'^agregar-estudios/(?P<id>\w+)$',
        AgregarEstudios.as_view(),
        name='agregar_estudios'
    ),
    url(
        r'^modificar-estudios/(?P<id>\w+)$',
        ModificarEstudios.as_view(),
        name='modificar_estudios'
    ),
    url(
        r'^eliminar-estudios/(?P<id>\w+)$',
        'medico.controllers.eliminar_estudios',
        name='eliminar_estudios'
    ),
    url(
        r'^agregar-reconocimientos/(?P<id>\w+)$',
        AgregarReconocimientos.as_view(),
        name='agregar_reconocimientos'
    ),
    url(
        r'^modificar-reconocimientos/(?P<id>\w+)$',
        ModificarReconocimientos.as_view(),
        name='modificar_reconocimientos'
    ),
    url(
        r'^eliminar-reconocimientos/(?P<id>\w+)$',
        'medico.controllers.eliminar_reconocimientos',
        name='eliminar_reconocimientos'
    ),
    url(
        r'^agregar-publicaciones/(?P<id>\w+)$',
        AgregarPublicaciones.as_view(),
        name='agregar_publicaciones'
    ),
    url(
        r'^modificar-publicaciones/(?P<id>\w+)$',
        ModificarPublicaciones.as_view(),
        name='modificar_publicaciones'
    ),
    url(
        r'^eliminar-publicaciones/(?P<id>\w+)$',
        'medico.controllers.eliminar_publicaciones',
        name='eliminar_publicaciones'
    ),
    url(
        r'^agregar-experiencias/(?P<id>\w+)$',
        AgregarExperiencias.as_view(),
        name='agregar_experiencias'
    ),
    url(
        r'^modificar-experiencias/(?P<id>\w+)$',
        ModificarExperiencias.as_view(),
        name='modificar_experiencias'
    ),
    url(
        r'^eliminar-experiencias/(?P<id>\w+)$',
        'medico.controllers.eliminar_experiencias',
        name='eliminar_experiencias'
    ),
    url(
        r'^agregar-habilidades/(?P<id>\w+)$',
        AgregarHabilidades.as_view(),
        name='agregar_habilidades'
    ),
    url(
        r'^modificar-habilidades/(?P<id>\w+)$',
        ModificarHabilidades.as_view(),
        name='modificar_habilidades'
    ),
    url(
        r'^eliminar-habilidades/(?P<id>\w+)$',
        'medico.controllers.eliminar_habilidades',
        name='eliminar_habilidades'
    ),
    url(
        r'^agregar-eventos/(?P<id>\w+)$',
        AgregarEventos.as_view(),
        name='agregar_eventos'
    ),
    url(
        r'^modificar-eventos/(?P<id>\w+)$',
        ModificarEventos.as_view(),
        name='modificar_eventos'
    ),
    url(
        r'^eliminar-eventos/(?P<id>\w+)$',
        'medico.controllers.eliminar_eventos',
        name='eliminar_eventos'
    ),
    url(
        r'^ver-consultas/(?P<id>\w+)$',
        VerConsultas.as_view(),
        name='ver_consultas'
    ),
    url(
        r'^agregar-consulta/(?P<id>\w+)$',
        AgregarConsulta.as_view(),
        name='agregar_consulta'
    ),
    url(
        r'^modificar-consulta/(?P<user>\w+)/(?P<id>\w+)$',
        ModificarConsultas.as_view(),
        name='modificar_consulta'
    ),
    url(
        r'^eliminar-consulta/(?P<id>\w+)$',
        'medico.controllers.eliminar_consultas',
        name='eliminar_consulta'
    ),
    url(
        r'^buscar-paciente$',
        BuscarPaciente.as_view(),
        name='buscar_paciente'
    ),
    url(
        r'^buscar-medico$',
        BuscarMedico.as_view(),
        name='buscar_medico'
    ),
    url(
        r'^ver-citas/(?P<id>\w+)$',
        VerCitas.as_view(),
        name='ver_citas'
    ),
    url(
        r'^agregar-cita/(?P<id>\w+)$',
        AgregarCitas.as_view(),
        name='agregar_cita'
    ),
    url(
        r'^modificar-cita/(?P<id>\w+)$',
        ModificarCitas.as_view(),
        name='modificar_cita'
    ),
    url(
        r'^eliminar-cita/(?P<id>\w+)$',
        'medico.controllers.eliminar_citas',
        name='eliminar_cita'
    ),
    url(
        r'^historias/$',
        HistoriasClinicas.as_view(),
        name='historias_clinicas'
    ),
    url(
        r'^historias/new/$',
        HistoriasClinicasCrear.as_view(),
        name='crear_historias_clinicas'
    ),
    url(
        r'^ver-historia-clinica/(?P<pk>\w+)$',
        HistoriasClinicasModificar.as_view(),
        name='ver_historia_clinica'
    ),
    url(
        r'^eliminar-historia_clinica/(?P<id>\w+)$',
        'medico.controllers.eliminar_historia_clinica',
        name='eliminar_historia_clinica'
    ),
    url(
        r'^consulta/(?P<id>\w+)$',
        Consultas.as_view(),
        name='consulta'
    ),
    url(
        r'^comenzar-revision/(?P<id>\w+)$',
        ComenzarRevision.as_view(),
        name='comenzar_revision'
    ),
    url(
        r'^informe-medico/(?P<id>\w+)$',
        InformeMedico.as_view(),
        name='informe_medico'
    ),

    url(
        r'^pdf-informe/(?P<id>\w+)$',
        MyPDFView.as_view(),
        name='generarPDF'
    ),
    url(
        r'^referir-paciente/(?P<id>\w+)$',
        ReferirPaciente.as_view(),
        name='referir_paciente'
    ),
    url(
        r'^ver-historial/(?P<id>\w+)$',
        VerHistorial.as_view(),
        name='ver_historial'
    ),
    url(
        r'^solicitud-examen/$',
        SolicitudExamen.as_view(),
        name='solicitud-examen'
    ),
]

medico/models.py
from django.db import models
from administrador.models import *
from paciente.models import *
from django.core.validators import MaxValueValidator
from django.utils import timezone

class Medico(models.Model):
	cedula = models.IntegerField(primary_key=True,
								 validators=[MaxValueValidator(99999999)])
	first_name = models.CharField(max_length=30, blank=True, null=True)
	last_name = models.CharField(max_length=30, blank=True, null=True)
	fecha_nacimiento = models.DateField(null=True)
	sexo = models.CharField(max_length=10, blank=True, null=True)
	estado_civil = models.CharField(max_length=15, blank=True, null=True)
	telefono = models.CharField(max_length=15, blank=True, null=True)
	direccion = models.CharField(max_length=100, blank=True, null=True)
	usuario = models.ForeignKey(Usuario,
								on_delete=models.CASCADE)

	def __str__(self):
		return str(self.cedula) + " " + self.first_name + " " + self.last_name

class Especialidad(models.Model):
	nombre_especialidad = models.CharField(primary_key=True, max_length=30)

	def __str__(self):
		return str(self.nombre_especialidad)

class Institucion(models.Model):
	TIPO = (
			('Hospital', 'Hospital'),
			('Clinica', 'Clinica'),
			('Laboratorio', 'Laboratorio')
			)
	rif = models.CharField(max_length=12, blank=False)
	name = models.CharField(max_length=100)
	address = models.CharField(max_length=255, blank=False)
	tipo = models.CharField(max_length=30, choices=TIPO, blank=False, default='')

	def __str__(self):
		return self.name

class Laboratorio(models.Model):
	institucion = models.ForeignKey(Institucion,
									on_delete= models.CASCADE)
	rif = models.CharField(max_length=12, blank=False)
	name = models.CharField(max_length=100)
	address = models.CharField(max_length=255, blank=False)
	regent = models.CharField(max_length=100)

	def __str__(self):
		return str(self.name)

# Se contempla tener aqui donde trabaja el medico y la especialidad
class Medico_Especialidad(models.Model):
	especialidad = models.ForeignKey(Especialidad,
									 on_delete=models.CASCADE)
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	institucion = models.ForeignKey(Institucion,
									on_delete= models.CASCADE)
	horario = models.CharField(max_length=1000, blank=False)

	def __str__(self):
		return str(self.horario)


class Medico_Estudios(models.Model):
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	titulo = models.CharField(max_length=500, blank=False)
	fecha_graduacion = models.DateField()
	descripcion = models.CharField(max_length=500, blank=False)
	institucion = models.CharField(max_length=500, blank=False)


class Medico_Habilidades(models.Model):
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	titulo = models.CharField(max_length=500, blank=False)
	descripcion = models.CharField(max_length=500, blank=False)


class Medico_Experiencias(models.Model):
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	titulo = models.CharField(max_length=500, blank=False)
	descripcion = models.CharField(max_length=500, blank=False)
	fecha_inicio = models.DateField()
	fecha_fin = models.DateField()
	institucion = models.CharField(max_length=500, blank=False)


class Medico_Logros(models.Model):
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	titulo = models.CharField(max_length=500, blank=False)
	fecha = models.DateField()
	descripcion = models.CharField(max_length=500, blank=False)


class Medico_Publicaciones(models.Model):
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	titulo = models.CharField(max_length=100, blank=False)
	autores = models.CharField(max_length=100, blank=False)
	descripcion = models.CharField(max_length=500, blank=False)
	revista = models.CharField(max_length=100, blank=False)
	numero = models.CharField(max_length=5, blank=False)
	volumen = models.CharField(max_length=5, blank=False)
	fecha = models.DateField()


class Medico_Eventos(models.Model):
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	titulo = models.CharField(max_length=500, blank=False)
	descripcion = models.CharField(max_length=500, blank=False)
	institucion = models.CharField(max_length=500, blank=False)
	date = models.DateField()


class Medico_Citas(models.Model):
	HORARIOS = (
				("6Am","6Am"),
				("7Am","7Am"),
				("8Am","8Am"),
				("9Am","9Am"),
				("10Am","10Am"),
				("11Am","11Am"),
				("12Pm","12Pm"),
				("1Pm","1Pm"),
				("2Pm","2Pm"),
				("3Pm","3Pm"),
				("4Pm","4Pm"),
				("5Pm","5Pm")
				)
	paciente = models.ForeignKey(Paciente,
								 on_delete=models.CASCADE)
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	institucion = models.ForeignKey(Institucion,
									on_delete=models.CASCADE)
	fecha = models.DateField()
	descripcion = models.CharField(max_length=500, blank=False)
	hora = models.CharField(max_length=5, choices=HORARIOS,blank=False)
	especialidad = models.ForeignKey(Especialidad,
									 on_delete=models.CASCADE)
	revision = models.BooleanField(default=False)
	informe = models.BooleanField(default=False)
	es_referido = models.BooleanField(default=False)

	def __unicode__(self):
		return self.name

	class Meta:
		unique_together = ("paciente","medico","institucion","fecha")

class Medico_Revision(models.Model):
	cita = models.OneToOneField(Medico_Citas, on_delete=models.CASCADE, primary_key= True,)
	motivos = models.CharField(max_length=500, blank=False)
	sintomas = models.CharField(max_length=500, blank=False)
	presion_sanguinea_diastolica = models.IntegerField(blank=False, default=0)
	presion_sanguinea_sistolica =models.IntegerField(blank=False, default=0)
	temperatura =models.IntegerField(blank=False, default=0)
	frec_respiratoria =models.IntegerField(blank=False, default=0)
	frec_cardiaca =models.IntegerField(blank=False, default=0)
	otros = models.CharField(max_length=100, blank=True)


class Medico_Informe(models.Model):
	medico_Revision = models.ForeignKey(Medico_Revision,
										on_delete=models.CASCADE)
	desc_prediagnostico = models.TextField(max_length=100)
	recipe_medico = models.TextField()


class Referencia(models.Model):

	HORARIOS = (
				("6Am","6Am"),
				("7Am","7Am"),
				("8Am","8Am"),
				("9Am","9Am"),
				("10Am","10Am"),
				("11Am","11Am"),
				("12Pm","12Pm"),
				("1Pm","1Pm"),
				("2Pm","2Pm"),
				("3Pm","3Pm"),
				("4Pm","4Pm"),
				("5Pm","5Pm")
				)
	cita = models.ForeignKey(Medico_Citas,
										on_delete=models.CASCADE)
	paciente = models.ForeignKey(Paciente,
								 on_delete=models.CASCADE)
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	institucion = models.ForeignKey(Institucion,
									on_delete=models.CASCADE)
	fecha = models.DateField()
	descripcion = models.CharField(max_length=500, blank=False)
	hora = models.CharField(max_length=5, choices=HORARIOS,blank=False)
	especialidad = models.ForeignKey(Especialidad,
									on_delete=models.CASCADE)
	archivo = models.FileField(upload_to='informes/')

class SolicitudExamen(models.Model):
	fecha = models.DateTimeField(default=timezone.now)
	tipoexamen = models.ForeignKey(Tipoexamen, on_delete = models.CASCADE)
	laboratorio = models.ForeignKey(Laboratorio, on_delete = models.CASCADE)
	paciente = models.ForeignKey(Paciente, on_delete = models.CASCADE)

eHealth/templates/medico/agregar_eventos.html
{% extends "base.html" %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
{% block content %}
  <div id="cuerpoHeredado">
    <br>
    <h2>{{title}} Eventos</h2>
    <form action="" method=POST>

      {% csrf_token %}
      <div class="hidden">
          {% bootstrap_form_errors form %}
      </div>
      <label for="id_titulo">Título</label>
      {% bootstrap_field form.titulo layout="inline" %}
      <label for="id_descripcion">Descripción</label>
      {% bootstrap_field form.descripcion layout="inline" %}
      <label for="id_institucion">Institución</label>
      {% bootstrap_field form.institucion layout="inline" %}
      <label for="id_date">Fecha</label>
      {% bootstrap_field form.date layout="inline" %}
      {% buttons %}
        <div class="col-md-3"></div>
        <div class="col-sm-4 col-md-6 text-center">
            <br>
            <button id="id_submit" type="submit" class="btn btn-lg calculate">
                Guardar
            </button>
            <br>
            <br>
        </div>
        <div class="col-md-3"></div>
    {% endbuttons %}
    </form>
  </div>
{% endblock %}
{% block custom_script %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<script src="{% static 'plugins/datepicker/locales/bootstrap-datepicker.es.js' %}"></script>
<script type="text/javascript">
  $(document).ready(function(){
  $( "#id_date" ).datepicker({ format: 'yyyy-mm-dd' });
});
</script>
{% endblock %}

eHealth/templates/medico/agregar_experiencias.html
{% extends "base.html" %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
{% block content %}
  <div id="cuerpoHeredado">
    <br>
    <h2>{{title}} Experiencias</h2>
    <form action="" method=POST>

      {% csrf_token %}
      <div class="hidden">
          {% bootstrap_form_errors form %}
      </div>
      <label for="id_titulo">Título</label>
      {% bootstrap_field form.titulo layout="inline" %}
      <label for="id_descripcion">Descripción</label>
      {% bootstrap_field form.descripcion layout="inline" %}
      <label for="id_fecha_inicio">Fecha inicio</label>
      {% bootstrap_field form.fecha_inicio layout="inline" %}
      <label for="id_fecha_fin">Fecha fin</label>
      {% bootstrap_field form.fecha_fin layout="inline" %}
      <label for="id_institucion">Institución</label>
      {% bootstrap_field form.institucion layout="inline" %}
      {% buttons %}
        <div class="col-md-3"></div>
        <div class="col-sm-4 col-md-6 text-center">
            <br>
            <button id="id_submit" type="submit" class="btn btn-lg calculate">
                Guardar
            </button>
            <br>
            <br>
        </div>
        <div class="col-md-3"></div>
    {% endbuttons %}
    </form>
  </div>
{% endblock %}
{% block custom_script %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<script src="{% static 'plugins/datepicker/locales/bootstrap-datepicker.es.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
  $( "#id_fecha_inicio" ).datepicker({ format: 'yyyy-mm-dd' });
  $( "#id_fecha_fin" ).datepicker({ format: 'yyyy-mm-dd' });
});
</script>
{% endblock %}

eHealth/templates/medico/agregar_publicaciones.html
{% extends "base.html" %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
{% block content %}
  <div id="cuerpoHeredado">
    <br>
    <h2>{{title}} Publicaciones</h2>
    <form action="" method=POST>

      {% csrf_token %}
      <div class="hidden">
          {% bootstrap_form_errors form %}
      </div>
      <label for="id_titulo">Título</label>
      {% bootstrap_field form.titulo layout="inline" %}
      <label for="id_autores">Autores</label>
      {% bootstrap_field form.autores layout="inline" %}
      <label for="id_descripcion">Descripción</label>
      {% bootstrap_field form.descripcion layout="inline" %}
      <label for="id_revista">Revista</label>
      {% bootstrap_field form.revista layout="inline" %}
      <label for="id_numero">Número</label>
      {% bootstrap_field form.numero layout="inline" %}
      <label for="id_volumen">Volumen</label>
      {% bootstrap_field form.volumen layout="inline" %}
      <label for="id_fecha">Fecha</label>
      {% bootstrap_field form.fecha layout="inline" %}
      {% buttons %}
        <div class="col-md-3"></div>
        <div class="col-sm-4 col-md-6 text-center">
            <br>
            <button id="id_submit" type="submit" class="btn btn-lg calculate">
                Guardar
            </button>
            <br>
            <br>
        </div>
        <div class="col-md-3"></div>
    {% endbuttons %}
    </form>
  </div>
{% endblock %}
{% block custom_script %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<script src="{% static 'plugins/datepicker/locales/bootstrap-datepicker.es.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
  $( "#id_fecha" ).datepicker({ format: 'yyyy-mm-dd' });
});
</script>
{% endblock %}

eHealth/templates/medico/agregar_reconocimientos.html
{% extends "base.html" %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
{% block content %}
  <div id="cuerpoHeredado">
    <br>
    <h2>{{title}} reconocimientos</h2>
    <form action="" method=POST>

      {% csrf_token %}
      <div class="hidden">
          {% bootstrap_form_errors form %}
      </div>
      <label for="id_titulo">Título</label>
      {% bootstrap_field form.titulo layout="inline" %}
      <label for="id_fecha">Fecha</label>
      {% bootstrap_field form.fecha layout="inline" %}
      <label for="id_descripcion">Descripción</label>
      {% bootstrap_field form.descripcion layout="inline" %}
      {% buttons %}
        <div class="col-md-3"></div>
        <div class="col-sm-4 col-md-6 text-center">
            <br>
            <button id="id_submit" type="submit" class="btn btn-lg calculate">
                Guardar
            </button>
            <br>
            <br>
        </div>
        <div class="col-md-3"></div>
    {% endbuttons %}
    </form>
  </div>
{% endblock %}
{% block custom_script %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<script src="{% static 'plugins/datepicker/locales/bootstrap-datepicker.es.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
  $( "#id_fecha" ).datepicker({ format: 'yyyy-mm-dd' });
});
</script>
{% endblock %}

eHealth/templates/medico/generarPDF.html
<!DOCTYPE html>

<head>

   <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

</head>

<body>

    </br>

<a href="{% url "pagina_detalle"  slug=object.slug %}"> Generar PDF de {{object.title}}</a>

<h1>{{ entry.title }}</h1>



    <i>{{entry.modified}}</i>

        {{entry.body|safe}}

</body>

eHealth/templates/medico/referir_paciente.html
{% extends "base_m.html" %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
{% block content %}

<div id="cuerpoHeredado">

      <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#refeir">Referir a Médico</a></li>
        <li><a data-toggle="tab" href="#menu1">Referir a Laboratorio</a></li>
      </ul>

    <div class="tab-content">
    <div id="menu1" class="tab-pane fade">
          <center><h2>Referenciar a Laboratorio</h2></center>
          <br>
        <div class="col-md-6 col-sm-16 col-xs-20">
        <h3 for="">Nombre del Paciente</h3>
        <span>{{consulta.paciente.first_name}} {{consulta.paciente.last_name}}</span>
        <h3 for="">CI del Paciente</h3>
        <span>{{consulta.paciente.cedula}}</span>
        </div>
    </div>
    <div id="referir" class="tab-pane fade in active">

    <div class="col-md-10 col-sm-10 col-xs-12 personal-info">
      {% if form.is_multipart %}
      <form enctype="multipart/form-data" method="POST" action="{% url 'referir_paciente' consulta.id %}">
      {% else %}
      <form action="{% url 'referir_paciente' consulta.id %}" method=POST>
      {% endif %}
        {% csrf_token %}

	    <div class="hidden">
	        {% bootstrap_form_errors form %}
	    </div>


  	    {% if messages %}
  	    <ul class="messages">
  	      {% for mes in messages %}
  	      <li{% if mes.tags  %}
  	      class="{{ mes.tag }}"
  	      {% endif%}>{{ mes }}
  	      </li>
  	      {% endfor %}
  	    </ul>
  	    {% endif %}

        {% if form.errors %}
          {% for field in form %}
              {% for error in field.errors %}
                  <div class="alert alert-danger">
                      <strong>{{ error|escape }}</strong>
                  </div>
              {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                  <strong>{{ error|escape }}</strong>
              </div>
          {% endfor %}
        {% endif %}

        <center><h2>Referenciar a Médico</h2></center>
          <br>

        <div class="col-md-16 col-sm-16 col-xs-20">
        <label for="">Nombre del Paciente</label>
        <span>{{consulta.paciente.first_name}} {{consulta.paciente.last_name}}</span>
        <label for="">CI del Paciente</label>
        <span>{{consulta.paciente.cedula}}</span>

          <label for="id_medico">Médico</label>
 	       {% bootstrap_field form.medico layout="inline" %}
 	      <label for="id_inst">Institución Médica</label>
 	      {% bootstrap_field form.institucion layout="inline" %}
 	      <label for="id_especialidad">Especialidad</label>
 	      {% bootstrap_field form.especialidad layout="inline" %}
 	      <label for="id_fecha">Fecha</label>
 	      {% bootstrap_field form.fecha layout="inline" %}
 	      <label for="id_hora">Hora</label>
 	        {% bootstrap_field form.hora layout="inline" %}
 	      <label for="id_descripcion">Descripción</label>
          {% bootstrap_field form.descripcion layout="inline" %}
        <label for="id_archivo">Adjuntar Informe</label>
         {{ form.archivo   }}

	      {% buttons %}
	        <div class="col-md-3"></div>
	        <div class="col-sm-4 col-md-6 text-center">
	            <br>
	            <button id="id_submit" type="submit" class="btn btn-lg calculate" onclick="obtenerId()">
	                Guardar
	            </button>
	            <br>
	            <br>
	        </div>
	        <div class="col-md-3"></div>
          <div class="col-md-3"></div>
          </div>
	    {% endbuttons %}
    </form>
    </form>
    <div class="col-md-3"></div>
  </div>
{% endblock %}
{% block custom_script %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<script src="{% static 'plugins/datepicker/locales/bootstrap-datepicker.es.js' %}"></script>

<script type="text/javascript">
$(document).ready(function(){
  $( "#id_fecha" ).datepicker({ format: 'yyyy-mm-dd' });
});
</script>

<script type="text/javascript">
  function getGET(){
   var loc = document.location.href;
   var getString = loc.split('_')[1];
   var GET = getString.split('&');
   var get = {};//this object will be filled with the key-value pairs and returned.

   for(var i = 0, l = GET.length; i < l; i++){
      var tmp = GET[i].split('=');
      get[tmp[0]] = unescape(decodeURI(tmp[1]));
   }
   return get;
}
</script>

<script type="text/javascript">
  function obtenerId(){
    var valores=getGET();
    alert(valores);
    if(valores) {
      var medico = valores[id];
    }
    document.getElementById("id_medico2").value = medico;
    alert(document.getElementById("id_medico2").value());
  }
</script>

{% endblock %}