eHealth/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('administrador.urls')),
    url(r'^medico/', include('medico.urls')),
    url(r'^paciente/', include('paciente.urls')),
    ]

medico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve
from medico.views import *


urlpatterns = [
    url(
        r'^perfil-medico/(?P<id>\w+)$',
        PerfilMedico.as_view(),
        name='perfil_medico'
    ),
    url(
        r'^agregar-estudios/(?P<id>\w+)$',
        AgregarEstudios.as_view(),
        name='agregar_estudios'
    ),
    url(
        r'^modificar-estudios/(?P<id>\w+)$',
        ModificarEstudios.as_view(),
        name='modificar_estudios'
    ),
    url(
        r'^eliminar-estudios/(?P<id>\w+)$',
        'medico.controllers.eliminar_estudios',
        name='eliminar_estudios'
    ),
    url(
        r'^agregar-reconocimientos/(?P<id>\w+)$',
        AgregarReconocimientos.as_view(),
        name='agregar_reconocimientos'
    ),
    url(
        r'^modificar-reconocimientos/(?P<id>\w+)$',
        ModificarReconocimientos.as_view(),
        name='modificar_reconocimientos'
    ),
    url(
        r'^eliminar-reconocimientos/(?P<id>\w+)$',
        'medico.controllers.eliminar_reconocimientos',
        name='eliminar_reconocimientos'
    ),
    url(
        r'^agregar-publicaciones/(?P<id>\w+)$',
        AgregarPublicaciones.as_view(),
        name='agregar_publicaciones'
    ),
    url(
        r'^modificar-publicaciones/(?P<id>\w+)$',
        ModificarPublicaciones.as_view(),
        name='modificar_publicaciones'
    ),
    url(
        r'^eliminar-publicaciones/(?P<id>\w+)$',
        'medico.controllers.eliminar_publicaciones',
        name='eliminar_publicaciones'
    ),
    url(
        r'^agregar-experiencias/(?P<id>\w+)$',
        AgregarExperiencias.as_view(),
        name='agregar_experiencias'
    ),
    url(
        r'^modificar-experiencias/(?P<id>\w+)$',
        ModificarExperiencias.as_view(),
        name='modificar_experiencias'
    ),
    url(
        r'^eliminar-experiencias/(?P<id>\w+)$',
        'medico.controllers.eliminar_experiencias',
        name='eliminar_experiencias'
    ),
    url(
        r'^agregar-habilidades/(?P<id>\w+)$',
        AgregarHabilidades.as_view(),
        name='agregar_habilidades'
    ),
    url(
        r'^modificar-habilidades/(?P<id>\w+)$',
        ModificarHabilidades.as_view(),
        name='modificar_habilidades'
    ),
    url(
        r'^eliminar-habilidades/(?P<id>\w+)$',
        'medico.controllers.eliminar_habilidades',
        name='eliminar_habilidades'
    ),
    url(
        r'^agregar-eventos/(?P<id>\w+)$',
        AgregarEventos.as_view(),
        name='agregar_eventos'
    ),
    url(
        r'^modificar-eventos/(?P<id>\w+)$',
        ModificarEventos.as_view(),
        name='modificar_eventos'
    ),
    url(
        r'^eliminar-eventos/(?P<id>\w+)$',
        'medico.controllers.eliminar_eventos',
        name='eliminar_eventos'
    ),
    url(
        r'^ver-consultas/(?P<id>\w+)$',
        VerConsultas.as_view(),
        name='ver_consultas'
    ),
    url(
        r'^agregar-consulta/(?P<id>\w+)$',
        AgregarConsulta.as_view(),
        name='agregar_consulta'
    ),
    url(
        r'^modificar-consulta/(?P<user>\w+)/(?P<id>\w+)$',
        ModificarConsultas.as_view(),
        name='modificar_consulta'
    ),
    url(
        r'^eliminar-consulta/(?P<id>\w+)$',
        'medico.controllers.eliminar_consultas',
        name='eliminar_consulta'
    ),
    url(
        r'^buscar-paciente$',
        BuscarPaciente.as_view(),
        name='buscar_paciente'
    ),
    url(
        r'^buscar-medico$',
        BuscarMedico.as_view(),
        name='buscar_medico'
    ),
    url(
        r'^ver-citas/(?P<id>\w+)$',
        VerCitas.as_view(),
        name='ver_citas'
    ),
    url(
        r'^agregar-cita/(?P<id>\w+)$',
        AgregarCitas.as_view(),
        name='agregar_cita'
    ),
    url(
        r'^modificar-cita/(?P<id>\w+)$',
        ModificarCitas.as_view(),
        name='modificar_cita'
    ),
    url(
        r'^eliminar-cita/(?P<id>\w+)$',
        'medico.controllers.eliminar_citas',
        name='eliminar_cita'
    ),
    url(
        r'^historias/$',
        HistoriasClinicas.as_view(),
        name='historias_clinicas'
    ),
    url(
        r'^historias/new/$',
        HistoriasClinicasCrear.as_view(),
        name='crear_historias_clinicas'
    ),
    url(
        r'^ver-historia-clinica/(?P<pk>\w+)$',
        HistoriasClinicasModificar.as_view(),
        name='ver_historia_clinica'
    ),
    url(
        r'^eliminar-historia_clinica/(?P<id>\w+)$',
        'medico.controllers.eliminar_historia_clinica',
        name='eliminar_historia_clinica'
    ),
    url(
        r'^consulta/(?P<id>\w+)$',
        Consultas.as_view(),
        name='consulta'
    ),
    url(
        r'^comenzar-revision/(?P<id>\w+)$',
        ComenzarRevision.as_view(),
        name='comenzar_revision'
    ),
    url(
        r'^informe-medico/(?P<id>\w+)$',
        InformeMedico.as_view(),
        name='informe_medico'
    ),

    url(
        r'^pdf-informe/(?P<id>\w+)$',
        MyPDFView.as_view(),
        name='generarPDF'
    ),
    url(
        r'^referir-paciente/(?P<id>\w+)$',
        ReferirPaciente.as_view(),
        name='referir_paciente'
    ),
    url(
        r'^ver-historial/(?P<id>\w+)$',
        VerHistorial.as_view(),
        name='ver_historial'
    ),
    url(
        r'^solicitud-examen/$',
        SolicitudExamen.as_view(),
        name='solicitud-examen'
    ),
]

paciente/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from paciente.views import *
from medico.views import *

urlpatterns = [
    url(
        r'^ver-citas/(?P<id>\w+)$',
        VerCitas.as_view(),
        name='ver_citas_pac'
    ),
    url(
        r'^agregar-cita/(?P<id>\w+)$',
        AgregarCitasPaciente.as_view(),
        name='agregar_cita_pac'
    ),
    url(
        r'^modificar-cita/(?P<id>\w+)$',
        ModificarCitasPaciente.as_view(),
        name='modificar_cita_pac'
    ),
    url(
        r'^eliminar-cita/(?P<id>\w+)$',
        'medico.controllers.eliminar_citas',
        name='eliminar_cita_paciente'
    ),
    url(
        r'^buscar-medico$',
        BuscarMedico.as_view(),
        name='buscar_medico_paciente'
    ),
    url(
        r'^perfil-paciente/(?P<id>\w+)$',
        Perfil.as_view(),
        name='perfil_paciente'
    ),
    url(
        r'^informe-paciente/(?P<id>\w+)$',
        Informe.as_view(),
        name='informe_med'
    ),
    url(
        r'^ver-examenes/(?P<id>\w+)$',
        VerExamenesPaciente.as_view(),
        name='ver_examenes_paciente'
    ),
    url(
        r'^ver-detalles-examen/(?P<examen_id>\w+)$',
        DetallesExamenPaciente.as_view(),
        name='ver_detalles_examen_paciente'
    ),
]

paciente/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from medico.models import *
from django.utils import timezone

class Paciente(models.Model):
	ESTADOS_CIVILES = (
		('Soltero', 'Soltero'),
		('Casado', 'Casado'),
	)
	cedula = models.IntegerField(primary_key=True,
								 validators=[MaxValueValidator(99999999)])
	first_name = models.CharField(max_length=30, blank=True, null=True)
	last_name = models.CharField(max_length=30, blank=True, null=True)
	fecha_nacimiento = models.DateField(blank=True, null=True)
	lugar_nacimiento = models.CharField(max_length=70, blank=True, null=True)
	sexo = models.CharField(max_length=10, blank=True, null=True)
	estado_civil = models.CharField(max_length=7, choices=ESTADOS_CIVILES, blank=True, null=True)
	ocupacion = models.CharField(max_length=30, blank=True, null=True)
	direccion = models.CharField(max_length=70, blank=True, null=True)
	telefono = models.CharField(max_length=13, blank=True, null=True)
	usuario = models.ForeignKey(Usuario,
								on_delete=models.CASCADE)


	def __str__(self):
		return str(self.cedula) + "  " + self.first_name + " " + self.last_name


class Historiadetriaje(models.Model):
	paciente = models.ForeignKey(Paciente,
								 on_delete=models.CASCADE)
	medico_triaje = models.ForeignKey('medico.Medico',
	                                  on_delete=models.CASCADE)
	antecedentes_personales = models.CharField(max_length=500)
	antecedentes_familiares = models.CharField(max_length=500)
	motivo_consulta = models.CharField(max_length=200)
	enfermedad_actual = models.CharField(max_length=200)
	peso = models.DecimalField(max_digits=5,decimal_places=2)
	talla = models.DecimalField(max_digits=5,decimal_places=2)
	signos_vitales = models.CharField(max_length=200)
	piel = models.CharField(max_length=200)
	ojos = models.CharField(max_length=200)
	fosas_nasales = models.CharField(max_length=200)
	conductos_auditivos = models.CharField(max_length=200)
	cavidad_oral = models.CharField(max_length=200)
	cuello = models.CharField(max_length=200)
	columna = models.CharField(max_length=200)
	torax = models.CharField(max_length=200)
	abdomen = models.CharField(max_length=200)
	extremidades = models.CharField(max_length=200)
	genitales = models.CharField(max_length=200)

class Historia(models.Model):
	paciente = models.ForeignKey(Paciente,
								 on_delete=models.CASCADE)
	medico = models.ForeignKey('medico.Medico',
	                           on_delete=models.CASCADE)                             
	especialidad = models.ForeignKey('medico.Especialidad',
	                                 on_delete=models.CASCADE)
 
class Tipoexamen(models.Model):
	nombretipo = models.CharField(primary_key=True, max_length=200)
	
	def __str__(self):
		return str(self.nombretipo)

class Examen(models.Model):
	paciente = models.ForeignKey(Paciente,
								 on_delete=models.CASCADE)
	bioanalista = models.ForeignKey('bioanalista.Bioanalista',
							   on_delete=models.CASCADE)
	laboratorio = models.ForeignKey('medico.Laboratorio',
					on_delete=models.CASCADE,
					null=True)
	tipoexamen = models.ForeignKey(Tipoexamen,
					on_delete=models.CASCADE,
					null=True)
	#fecha = models.DateTimeField(default=timezone.localtime(timezone.now()))
	fecha = models.DateTimeField(default=timezone.now)

class Medicion(models.Model):
	tipoexamen = models.ForeignKey(Tipoexamen,
					on_delete=models.CASCADE,
					null=True)
	nombremedicion = models.CharField(primary_key=True, max_length=200)
	unidad = models.CharField(max_length=50)
	rangoesperado = models.CharField(max_length=100)
	posicion = models.CharField(max_length=3, null=True)
	
class Resultadomedicion(models.Model):
	examen = models.ForeignKey(Examen, on_delete=models.CASCADE)
	medicion = models.ForeignKey(Medicion, on_delete=models.CASCADE)
	resultado = models.CharField(max_length=100)
	

   
	

paciente/controllers.py
from administrador.models import *
from medico.models import *
from paciente.models import *
import datetime
import parsedatetime as pdt
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect

def editar_paciente(user, nombre, apellido, sexo, ocupacion, fecha,
                    lugar, estado_civil, telefono, direccion, email, foto):
    try:
        usuario = Usuario.objects.get(user=user)
        user = User.objects.get(pk=usuario.user.pk)
        paciente = Paciente.objects.get(usuario=usuario)
        paciente.first_name = nombre
        user.first_name = nombre
        paciente.last_name = apellido
        user.last_name = apellido
        user.email = email
        user.save()
        print("save")
        paciente.sexo = sexo
        print("sexo")
        try:
            fecha = datetime.datetime.strptime(fecha,
                                               '%d-%m-%Y'
                                               ).strftime('%Y-%m-%d')
        except:
            if fecha is None:
                fecha = None
            else:
                cal = pdt.Calendar()
                now = datetime.datetime.now()
                fecha = cal.parseDT(fecha, now)[0]

        paciente.fecha_nacimiento = fecha
        print("fecha")
        paciente.lugar_nacimiento = lugar
        print("lug")
        paciente.ocupacion = ocupacion
        print("ocu")
        paciente.estado_civil = estado_civil
        print("estado")

        if (telefono == '') :
            pass
        else :
            paciente.telefono = telefono
        print("telf")
        paciente.direccion = direccion
        if foto != False :
            usuario.foto=foto
            usuario.fotosubida = True
        usuario.save()
        paciente.save()
        print("saveeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee")

        return True

    except:
        return False


def agregar_citas_paciente(user_pk, medico, institucion, descripcion, fecha, hora, especialidad, es_referido):
    try:
        user = User.objects.get(pk=user_pk)
        usuario = Usuario.objects.get(user=user)
        paciente = Paciente.objects.get(usuario=usuario)
        medico = Medico.objects.get(cedula=medico)
        institucion = Institucion.objects.get(id=institucion)
        especialidad = Especialidad.objects.get(nombre_especialidad=especialidad)
        try:
            fecha = datetime.datetime.strptime(fecha,
                                               '%d-%m-%Y'
                                               ).strftime('%Y-%m-%d')
        except:
            if fecha is None:
                fecha = None
            else:
                cal = pdt.Calendar()
                now = datetime.datetime.now()
                fecha = cal.parseDT(fecha, now)[0]

        cita = Medico_Citas(paciente=paciente,
                            medico=medico,
                            institucion = institucion,
                            descripcion=descripcion,
                            fecha=fecha,
                            hora=hora,
                            especialidad=especialidad,
                            es_referido = es_referido)
        cita.save()
        return True
    except:
        return False


def modificar_citas_paciente(cita_id, medico, institucion, descripcion,
                                  fecha,hora,especialidad, es_referido):
    try:
        cita = Medico_Citas.objects.get(
            pk=cita_id)

        try:
            fecha = datetime.datetime.strptime(fecha,
                                               '%d-%m-%Y'
                                               ).strftime('%Y-%m-%d')
        except:
            if fecha is None:
                fecha = None
            else:
                cal = pdt.Calendar()
                now = datetime.datetime.now()
                fecha = cal.parseDT(fecha, now)[0]
        medico = Medico.objects.get(cedula=medico)
        cita.medico = medico
        cita.hora = hora
        institucion = Institucion.objects.get(id=institucion)
        cita.institucion = institucion
        especialidad = Especialidad.objects.get(nombre_especialidad=especialidad)
        cita.especialidad = especialidad
        cita.descripcion = descripcion
        cita.fecha = fecha
        cita.save()
        return True
    except:
        return False

eHealth/templates/paciente/agregar_cita_paciente.html
{% extends "base.html" %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
{% block content %}
  <div id="cuerpoHeredado">
    <br>
    <h2>{{title}} Cita</h2>
    {% if title == "Agregar" %}
    <form action="" method=POST>
    {% else %}
    <form action="" method=POST>
    {% endif %}
    {% csrf_token %}
    <div class="hidden">
        {% bootstrap_form_errors form %}
    </div>
    
    {% if messages %}
    <ul class="messages">
      {% for mes in messages %}
      <li{% if mes.tags  %}
      class="{{ mes.tag }}"
      {% endif%}>{{ mes }}
      </li>
      {% endfor %}
    </ul>
    {% endif %}

      {% if user.groups.all.0.name == 'paciente' %}
        <label for="id_medico">Médico</label>
       {% bootstrap_field form.medico layout="inline" %}
      {% endif %}
      {% if user.groups.all.0.name == 'medico' %}
      <label for="id_paciente">Paciente</label>
      {% bootstrap_field form.paciente layout="inline" %}
      {% endif %}
      <label for="id_fecha">Institución Médica</label>
      {% bootstrap_field form.institucion layout="inline" %}
      <label for="id_fecha">Fecha</label>
      {% bootstrap_field form.fecha layout="inline" %}
      <label for="id_descripcion">Descripción</label>
      {% bootstrap_field form.descripcion layout="inline" %}
      {% buttons %}
        <div class="col-md-3"></div>
        <div class="col-sm-4 col-md-6 text-center">
            <br>
            <button id="id_submit" type="submit" class="btn btn-lg calculate">
                Guardar
            </button>
            <br>
            <br>
        </div>
        <div class="col-md-3"></div>
    {% endbuttons %}
    </form>
  </div>
{% endblock %}
{% block custom_script %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
<script src="{% static 'plugins/datepicker/locales/bootstrap-datepicker.es.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
  $( "#id_fecha" ).datepicker({ format: 'yyyy-mm-dd'});
});
</script>
{% endblock %}

eHealth/templates/paciente/informe_med.html
{% extends "base.html" %}
{% block content %}
<div id="cuerpoHeredado">
  <center><h2>Mi Historial de Consultas</h2></center>
  <div id="show-appointments"><table>
    <tr>
      <th>Fecha</th>
      <th>Médico</th>
      <th>Especialidad</th>
      <th>Institución</th>
    </tr>

    {% for a in appointments %}
      {% if a.informe == True%}

      <tr onclick="location.href='{% url 'generarPDF' a.pk %}'">
        <td>{{a.fecha}}</td>
        <td>{{a.medico.first_name}}{{a.medico.last_name}} </td>
        <td>{{a.especialidad}}</td>
        <td>{{a.institucion}}</td>

      </tr>
      {% endif %}
    {% endfor%}
  </table></div>

</div>
{% endblock %}

eHealth/templates/paciente/ver_citas_paciente.html
{% extends "base.html" %}
{% block content %}
<div id="cuerpoHeredado">
  <center><h2>Mis Citas</h2></center>
  <!-- Modal content -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Finalizar Consulta</h4>
        </div>
        <div class="modal-body">
          <p>¿Está seguro que desea eliminar esta consulta?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <a type="button" class="btn btn-primary" href="{% url 'ver_citas' user.pk %}" > Aceptar</a>
        </div>
      </div>

    </div>
  </div>
  <!--  -->
  <div id="show-appointments"><table>
    <tr>
      <th>Fecha</th>
      {% if user.groups.all.0.name == 'medico' %}
      <th>Paciente</th>
      {% else %}
      <th>Médico</th>
      {% endif %}
      <th>Institución</th>
      <th>Descripción</th>
      <th style="text-align: right">
        <a id="add_appointment" href="{% url 'agregar_cita_paciente' user.pk %}">
          <i class="fa fa-plus-circle" style="font-size:20px;color:white"></i>
        </a>
      </th>
    </tr>
    {% for a in appointments %}
    <!-- Modal content -->
    <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Finalizar Consulta</h4>
          </div>
          <div class="modal-body">
            <p>¿Está seguro que desea eliminar esta consulta?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <a type="button" class="btn btn-primary" href="{% url 'eliminar_cita' a.pk%}" > Aceptar</a>
          </div>
        </div>

      </div>
    </div>



      <tr>
        <td>{{a.fecha}}</td>
        {% if user.groups.all.0.name == 'medico' %}
        <td>{{a.paciente.first_name}} {{a.paciente.last_name}}</td>
        {% else %}
        <td>{{a.medico.first_name}} {{a.medico.last_name}}</td>
        {% endif %}
        <td>{{a.institucion.name}}</td>
        <td>{{a.descripcion}}</td>
        <td style="text-align: right">
          <a href="{% url 'modificar_cita_paciente' a.pk %}"><i class="fa fa-pencil" style="font-size:20px;color:#5882FA"></i></a>
          <a data-toggle="modal" data-target="#myModal" ><i class="fa fa-trash" style="font-size:20px;color:#5882FA"></i></a>
        </td>
      </tr>
    {% endfor%}
  </table></div>
  </div>
</div>
{% endblock %}

eHealth/templates/paciente/ver_detalles_examen_paciente.html
{% extends 'base.html' %} {% block content %}
<h1> {{test.tipoexamen}} </h1>
<h2> {{test.paciente}} </h2>

<div class="table-responsive">
    <table class="table">
        <tr>
            <th>Medicion</th>
            <th>Resultado</th>
            <th>Unidad de Medida</th>
            <th>Esperado</th>
        </tr>
        {% for result in results %}
        <tr>
            <td>{{result.medicion.nombremedicion}}</td>
            <td>{{result.resultado}}</td>
            <td>{{result.medicion.unidad}}</td>
            <td>{{result.medicion.rangoesperado}}</td>
        </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

eHealth/templates/paciente/ver_examenes_paciente.html
{% extends "base.html" %} {% block content %}
<div id="cuerpoHeredado">
    <center>
        <h2>Mis Examenes</h2>
    </center>

    <div id="show-tests" class="table-responsive">
        <table id="search_result" class="table display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Bioanalista</th>
                    <th>Laboratorio</th>
                    <th>Tipo Examen</th>
                </tr>
            </thead>
            <tbody>
                {% for t in tests %}
                <tr>
                    <td>{{t.fecha}}</td>
                    <td>{{t.bioanalista.first_name}} {{t.bioanalista.last_name}}</td>
                    <td>{{t.laboratorio.name}}</td>
                    <td>
                        <a href="{% url 'ver_detalles_examen_paciente' t.pk %}">
                            {{t.tipoexamen.nombretipo}}
                        </a>
                    </td>
                </tr>
                {% endfor%}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}