administrador/urls.py
from django.conf.urls import url, patterns
from administrador.views import *
from django.conf.urls.static import static

urlpatterns = patterns(
    '',
    url(
        r'^$',
        'administrador.views.user_login',
        name='index'
    ),
    url(
        r'^register/$',
        Register.as_view(),
        name='register'
    ),
    url(
        r'^register-bioanalista/(?P<user_id>\w+)$',
        RegisterBioanalista.as_view(),
        name='register-bioanalista'
    ),
    url(
        r'^login/$',
        'administrador.views.user_login',
        name='login'
    ),
    url(
        r'^logout/$',
        'django.contrib.auth.views.logout',
        {
            'next_page': '/'
        },
        name='logout'),
    url(
        r'^success/$',
        Success.as_view(),
        name='success'
    ),
    url(
        r'^home/$',
        Home.as_view(),
        name='home'
    ),
    url(
        r'^inbox/$',
        Inbox.as_view(),
        name='inbox'
    ),
    url(
        r'^ver-usuarios/$',
        VerUsuarios.as_view(),
        name='ver_usuarios'
    ),
    url(
        r'^modificar-usuario/(?P<pk>\w+)$',
        ModificarUsuario.as_view(),
        name='modificar_usuario'
    ),
    url(
        r'^eliminar-usuario/(?P<id>\w+)$',
        'administrador.controllers.eliminar_usuario',
        name='eliminar_usuario'
    ),
    url(
        r'^ver-roles/$',
        VerRoles.as_view(),
        name='ver_roles'
    ),
    url(
        r'^agregar_rol/(?P<name>\w+)$',
        'administrador.controllers.agregar_rol',
        name='agregar_rol'
    ),
    url(
        r'^ver-instituciones/$',
        VerInstituciones.as_view(),
        name='ver_instituciones'
    ),
    url(
        r'^agregar_institucion/$',
        AgregarInstitucion.as_view(),
        name='agregar_institucion'
    ),
    url(
        r'^modificar_institucion/(?P<pk>\w+)$',
        ModificarInstitucion.as_view(),
        name='modificar_institucion'
    ),
    url(
        r'^eliminar_institucion/(?P<pk>\w+)$',
        'administrador.controllers.eliminar_institucion',
        name='eliminar_institucion'
    ),
    url(
        r'^ver-laboratorios/$',
        VerLaboratorios.as_view(),
        name='ver_laboratorios'
    ),
    url(
        r'^agregar_laboratorio/$',
        AgregarLaboratorio.as_view(),
        name='agregar_laboratorio'
    ),
    url(
        r'^modificar_laboratorio/(?P<pk>\w+)$',
        ModificarLaboratorio.as_view(),
        name='modificar_laboratorio'
    ),
    url(
        r'^eliminar_laboratorio/(?P<pk>\w+)$',
        'administrador.controllers.eliminar_laboratorio',
        name='eliminar_laboratorio'
    ),
    url(
        r'^ver-especialidades/$',
        VerEspecialidades.as_view(),
        name='ver_especialidades'
    ),
    url(
        r'^agregar_especialidad/$',
        AgregarEspecialidad.as_view(),
        name='agregar_especialidad'
    ),
    url(
        r'^modificar_especialidad/(?P<pk>[\w\s]+)$',
        ModificarEspecialidad.as_view(),
        name='modificar_especialidad'
    ),
    url(
        r'^eliminar_especialidad/(?P<pk>[\w\s]+)$',
        'administrador.controllers.eliminar_especialidad',
        name='eliminar_especialidad'
    ),
    url(
        r'^agregar_roles/$',
        AgregarRoles.as_view(),
        name='agregar_roles'
    ),
    url(
        r'^eliminar_rol/(?P<pk>\w+)$',
        'administrador.controllers.eliminar_rol',
        name='eliminar_rol'
    ),
    url(
        r'^ver-tiposdeexamen/$',
        VerTiposdeExamen.as_view(),
        name='ver_tiposdeexamen'
    ),
    url(
        r'^agregar_tipodeexamen/$',
        AgregarTipodeExamen.as_view(),
        name='agregar_tipodeexamen'
    ),
    url(
        r'^modificar_tipodeexamen/(?P<pk>[\w\s]+)$',
        ModificarTipodeExamen.as_view(),
        name='modificar_tipodeexamen'
    ),
    url(
        r'^eliminar_tipodeexamen/(?P<pk>[\w\s]+)$',
        'administrador.controllers.eliminar_tipodeexamen',
        name='eliminar_tipodeexamen'
    ),
    url(
        r'^ver-mediciones/$',
        VerMediciones.as_view(),
        name='ver_mediciones'
    ),
    url(
        r'^agregar-medicion/$',
        AgregarMedicion.as_view(),
        name='agregar_medicion'
    ),
    url(
        r'^eliminar-medicion/(?P<pk>[\w\s]+)$',
        'administrador.controllers.eliminar_medicion',
        name='eliminar_medicion'
    ),
    url(
        r'^modificar-medicion/(?P<pk>[\w\s]+)$',
        ModificarMedicion.as_view(),
        name='modificar_medicion'
    ),
  
         
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eHealth/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('administrador.urls')),
    url(r'^medico/', include('medico.urls')),
    url(r'^paciente/', include('paciente.urls')),
    ]

medico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve
from medico.views import *


urlpatterns = [
    url(
        r'^perfil-medico/(?P<id>\w+)$',
        PerfilMedico.as_view(),
        name='perfil_medico'
    ),
    url(
        r'^agregar-estudios/(?P<id>\w+)$',
        AgregarEstudios.as_view(),
        name='agregar_estudios'
    ),
    url(
        r'^modificar-estudios/(?P<id>\w+)$',
        ModificarEstudios.as_view(),
        name='modificar_estudios'
    ),
    url(
        r'^eliminar-estudios/(?P<id>\w+)$',
        'medico.controllers.eliminar_estudios',
        name='eliminar_estudios'
    ),
    url(
        r'^agregar-reconocimientos/(?P<id>\w+)$',
        AgregarReconocimientos.as_view(),
        name='agregar_reconocimientos'
    ),
    url(
        r'^modificar-reconocimientos/(?P<id>\w+)$',
        ModificarReconocimientos.as_view(),
        name='modificar_reconocimientos'
    ),
    url(
        r'^eliminar-reconocimientos/(?P<id>\w+)$',
        'medico.controllers.eliminar_reconocimientos',
        name='eliminar_reconocimientos'
    ),
    url(
        r'^agregar-publicaciones/(?P<id>\w+)$',
        AgregarPublicaciones.as_view(),
        name='agregar_publicaciones'
    ),
    url(
        r'^modificar-publicaciones/(?P<id>\w+)$',
        ModificarPublicaciones.as_view(),
        name='modificar_publicaciones'
    ),
    url(
        r'^eliminar-publicaciones/(?P<id>\w+)$',
        'medico.controllers.eliminar_publicaciones',
        name='eliminar_publicaciones'
    ),
    url(
        r'^agregar-experiencias/(?P<id>\w+)$',
        AgregarExperiencias.as_view(),
        name='agregar_experiencias'
    ),
    url(
        r'^modificar-experiencias/(?P<id>\w+)$',
        ModificarExperiencias.as_view(),
        name='modificar_experiencias'
    ),
    url(
        r'^eliminar-experiencias/(?P<id>\w+)$',
        'medico.controllers.eliminar_experiencias',
        name='eliminar_experiencias'
    ),
    url(
        r'^agregar-habilidades/(?P<id>\w+)$',
        AgregarHabilidades.as_view(),
        name='agregar_habilidades'
    ),
    url(
        r'^modificar-habilidades/(?P<id>\w+)$',
        ModificarHabilidades.as_view(),
        name='modificar_habilidades'
    ),
    url(
        r'^eliminar-habilidades/(?P<id>\w+)$',
        'medico.controllers.eliminar_habilidades',
        name='eliminar_habilidades'
    ),
    url(
        r'^agregar-eventos/(?P<id>\w+)$',
        AgregarEventos.as_view(),
        name='agregar_eventos'
    ),
    url(
        r'^modificar-eventos/(?P<id>\w+)$',
        ModificarEventos.as_view(),
        name='modificar_eventos'
    ),
    url(
        r'^eliminar-eventos/(?P<id>\w+)$',
        'medico.controllers.eliminar_eventos',
        name='eliminar_eventos'
    ),
    url(
        r'^ver-consultas/(?P<id>\w+)$',
        VerConsultas.as_view(),
        name='ver_consultas'
    ),
    url(
        r'^agregar-consulta/(?P<id>\w+)$',
        AgregarConsulta.as_view(),
        name='agregar_consulta'
    ),
    url(
        r'^modificar-consulta/(?P<user>\w+)/(?P<id>\w+)$',
        ModificarConsultas.as_view(),
        name='modificar_consulta'
    ),
    url(
        r'^eliminar-consulta/(?P<id>\w+)$',
        'medico.controllers.eliminar_consultas',
        name='eliminar_consulta'
    ),
    url(
        r'^buscar-paciente$',
        BuscarPaciente.as_view(),
        name='buscar_paciente'
    ),
    url(
        r'^buscar-medico$',
        BuscarMedico.as_view(),
        name='buscar_medico'
    ),
    url(
        r'^ver-citas/(?P<id>\w+)$',
        VerCitas.as_view(),
        name='ver_citas'
    ),
    url(
        r'^agregar-cita/(?P<id>\w+)$',
        AgregarCitas.as_view(),
        name='agregar_cita'
    ),
    url(
        r'^modificar-cita/(?P<id>\w+)$',
        ModificarCitas.as_view(),
        name='modificar_cita'
    ),
    url(
        r'^eliminar-cita/(?P<id>\w+)$',
        'medico.controllers.eliminar_citas',
        name='eliminar_cita'
    ),
    url(
        r'^historias/$',
        HistoriasClinicas.as_view(),
        name='historias_clinicas'
    ),
    url(
        r'^historias/new/$',
        HistoriasClinicasCrear.as_view(),
        name='crear_historias_clinicas'
    ),
    url(
        r'^ver-historia-clinica/(?P<pk>\w+)$',
        HistoriasClinicasModificar.as_view(),
        name='ver_historia_clinica'
    ),
    url(
        r'^eliminar-historia_clinica/(?P<id>\w+)$',
        'medico.controllers.eliminar_historia_clinica',
        name='eliminar_historia_clinica'
    ),
    url(
        r'^consulta/(?P<id>\w+)$',
        Consultas.as_view(),
        name='consulta'
    ),
    url(
        r'^comenzar-revision/(?P<id>\w+)$',
        ComenzarRevision.as_view(),
        name='comenzar_revision'
    ),
    url(
        r'^informe-medico/(?P<id>\w+)$',
        InformeMedico.as_view(),
        name='informe_medico'
    ),

    url(
        r'^pdf-informe/(?P<id>\w+)$',
        MyPDFView.as_view(),
        name='generarPDF'
    ),
    url(
        r'^referir-paciente/(?P<id>\w+)$',
        ReferirPaciente.as_view(),
        name='referir_paciente'
    ),
    url(
        r'^ver-historial/(?P<id>\w+)$',
        VerHistorial.as_view(),
        name='ver_historial'
    ),
    url(
        r'^solicitud-examen/$',
        SolicitudExamen.as_view(),
        name='solicitud-examen'
    ),
]

medico/models.py
from django.db import models
from administrador.models import *
from paciente.models import *
from django.core.validators import MaxValueValidator
from django.utils import timezone

class Medico(models.Model):
	cedula = models.IntegerField(primary_key=True,
								 validators=[MaxValueValidator(99999999)])
	first_name = models.CharField(max_length=30, blank=True, null=True)
	last_name = models.CharField(max_length=30, blank=True, null=True)
	fecha_nacimiento = models.DateField(null=True)
	sexo = models.CharField(max_length=10, blank=True, null=True)
	estado_civil = models.CharField(max_length=15, blank=True, null=True)
	telefono = models.CharField(max_length=15, blank=True, null=True)
	direccion = models.CharField(max_length=100, blank=True, null=True)
	usuario = models.ForeignKey(Usuario,
								on_delete=models.CASCADE)

	def __str__(self):
		return str(self.cedula) + " " + self.first_name + " " + self.last_name

class Especialidad(models.Model):
	nombre_especialidad = models.CharField(primary_key=True, max_length=30)

	def __str__(self):
		return str(self.nombre_especialidad)

class Institucion(models.Model):
	TIPO = (
			('Hospital', 'Hospital'),
			('Clinica', 'Clinica'),
			('Laboratorio', 'Laboratorio')
			)
	rif = models.CharField(max_length=12, blank=False)
	name = models.CharField(max_length=100)
	address = models.CharField(max_length=255, blank=False)
	tipo = models.CharField(max_length=30, choices=TIPO, blank=False, default='')

	def __str__(self):
		return self.name

class Laboratorio(models.Model):
	institucion = models.ForeignKey(Institucion,
									on_delete= models.CASCADE)
	rif = models.CharField(max_length=12, blank=False)
	name = models.CharField(max_length=100)
	address = models.CharField(max_length=255, blank=False)
	regent = models.CharField(max_length=100)

	def __str__(self):
		return str(self.name)

# Se contempla tener aqui donde trabaja el medico y la especialidad
class Medico_Especialidad(models.Model):
	especialidad = models.ForeignKey(Especialidad,
									 on_delete=models.CASCADE)
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	institucion = models.ForeignKey(Institucion,
									on_delete= models.CASCADE)
	horario = models.CharField(max_length=1000, blank=False)

	def __str__(self):
		return str(self.horario)


class Medico_Estudios(models.Model):
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	titulo = models.CharField(max_length=500, blank=False)
	fecha_graduacion = models.DateField()
	descripcion = models.CharField(max_length=500, blank=False)
	institucion = models.CharField(max_length=500, blank=False)


class Medico_Habilidades(models.Model):
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	titulo = models.CharField(max_length=500, blank=False)
	descripcion = models.CharField(max_length=500, blank=False)


class Medico_Experiencias(models.Model):
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	titulo = models.CharField(max_length=500, blank=False)
	descripcion = models.CharField(max_length=500, blank=False)
	fecha_inicio = models.DateField()
	fecha_fin = models.DateField()
	institucion = models.CharField(max_length=500, blank=False)


class Medico_Logros(models.Model):
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	titulo = models.CharField(max_length=500, blank=False)
	fecha = models.DateField()
	descripcion = models.CharField(max_length=500, blank=False)


class Medico_Publicaciones(models.Model):
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	titulo = models.CharField(max_length=100, blank=False)
	autores = models.CharField(max_length=100, blank=False)
	descripcion = models.CharField(max_length=500, blank=False)
	revista = models.CharField(max_length=100, blank=False)
	numero = models.CharField(max_length=5, blank=False)
	volumen = models.CharField(max_length=5, blank=False)
	fecha = models.DateField()


class Medico_Eventos(models.Model):
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	titulo = models.CharField(max_length=500, blank=False)
	descripcion = models.CharField(max_length=500, blank=False)
	institucion = models.CharField(max_length=500, blank=False)
	date = models.DateField()


class Medico_Citas(models.Model):
	HORARIOS = (
				("6Am","6Am"),
				("7Am","7Am"),
				("8Am","8Am"),
				("9Am","9Am"),
				("10Am","10Am"),
				("11Am","11Am"),
				("12Pm","12Pm"),
				("1Pm","1Pm"),
				("2Pm","2Pm"),
				("3Pm","3Pm"),
				("4Pm","4Pm"),
				("5Pm","5Pm")
				)
	paciente = models.ForeignKey(Paciente,
								 on_delete=models.CASCADE)
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	institucion = models.ForeignKey(Institucion,
									on_delete=models.CASCADE)
	fecha = models.DateField()
	descripcion = models.CharField(max_length=500, blank=False)
	hora = models.CharField(max_length=5, choices=HORARIOS,blank=False)
	especialidad = models.ForeignKey(Especialidad,
									 on_delete=models.CASCADE)
	revision = models.BooleanField(default=False)
	informe = models.BooleanField(default=False)
	es_referido = models.BooleanField(default=False)

	def __unicode__(self):
		return self.name

	class Meta:
		unique_together = ("paciente","medico","institucion","fecha")

class Medico_Revision(models.Model):
	cita = models.OneToOneField(Medico_Citas, on_delete=models.CASCADE, primary_key= True,)
	motivos = models.CharField(max_length=500, blank=False)
	sintomas = models.CharField(max_length=500, blank=False)
	presion_sanguinea_diastolica = models.IntegerField(blank=False, default=0)
	presion_sanguinea_sistolica =models.IntegerField(blank=False, default=0)
	temperatura =models.IntegerField(blank=False, default=0)
	frec_respiratoria =models.IntegerField(blank=False, default=0)
	frec_cardiaca =models.IntegerField(blank=False, default=0)
	otros = models.CharField(max_length=100, blank=True)


class Medico_Informe(models.Model):
	medico_Revision = models.ForeignKey(Medico_Revision,
										on_delete=models.CASCADE)
	desc_prediagnostico = models.TextField(max_length=100)
	recipe_medico = models.TextField()


class Referencia(models.Model):

	HORARIOS = (
				("6Am","6Am"),
				("7Am","7Am"),
				("8Am","8Am"),
				("9Am","9Am"),
				("10Am","10Am"),
				("11Am","11Am"),
				("12Pm","12Pm"),
				("1Pm","1Pm"),
				("2Pm","2Pm"),
				("3Pm","3Pm"),
				("4Pm","4Pm"),
				("5Pm","5Pm")
				)
	cita = models.ForeignKey(Medico_Citas,
										on_delete=models.CASCADE)
	paciente = models.ForeignKey(Paciente,
								 on_delete=models.CASCADE)
	medico = models.ForeignKey(Medico,
							   on_delete=models.CASCADE)
	institucion = models.ForeignKey(Institucion,
									on_delete=models.CASCADE)
	fecha = models.DateField()
	descripcion = models.CharField(max_length=500, blank=False)
	hora = models.CharField(max_length=5, choices=HORARIOS,blank=False)
	especialidad = models.ForeignKey(Especialidad,
									on_delete=models.CASCADE)
	archivo = models.FileField(upload_to='informes/')

class SolicitudExamen(models.Model):
	fecha = models.DateTimeField(default=timezone.now)
	tipoexamen = models.ForeignKey(Tipoexamen, on_delete = models.CASCADE)
	laboratorio = models.ForeignKey(Laboratorio, on_delete = models.CASCADE)
	paciente = models.ForeignKey(Paciente, on_delete = models.CASCADE)

eHealth/templates/administrador/agregar_institucion.html
{% extends "base.html" %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
{% block content %}
  <div id="cuerpoHeredado">
    <br>
    <h2>{{title}} Institución</h2>
    {% if title == "Agregar" %}
    <form action="" method=POST>
    {% else %}
    <form action="" method=POST>
    {% endif %}
    {% csrf_token %}
    
    <div class="hidden">
        {% bootstrap_form_errors form %}
    </div>

    {% if messages %}
    <ul class="messages">
      {% for mes in messages %}
      <li{% if mes.tags  %}
      class="{{ mes.tag }}"
      {% endif%}>{{ mes }}
      </li>
      {% endfor %}
    </ul>
    {% endif %}

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <label for="id_rif"> Rif </label>
    {% bootstrap_field form.rif layout="inline" %}
    <label for="id_nombre">Nombre</label>
    {% bootstrap_field form.name layout="inline" %}
    <label for="id_direccion">Dirección</label>
    {% bootstrap_field form.address layout="inline" %}
    <label for="id_tipo">Tipo</label>
    {% bootstrap_field form.tipo layout="inline" %}
        {% buttons %}
        <div class="col-md-3"></div>
        <div class="col-sm-4 col-md-6 text-center">
            <br>
            <button id="id_submit" type="submit" class="btn btn-lg calculate" >
                Guardar
            </button>
            <br>
            <br>
        </div>
        <div class="col-md-3"></div>
    {% endbuttons %}
    </form>
  </div>
{% endblock %}

eHealth/templates/administrador/agregar_laboratorio.html
{% extends "base.html" %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
{% block content %}
  <div id="cuerpoHeredado">
    <br>
    <h2>{{title}} Laboratorio</h2>
    {% if title == "Agregar" %}
    <form action="" method=POST>
    {% else %}
    <form action="" method=POST>
    {% endif %}
    {% csrf_token %}
    
    <div class="hidden">
        {% bootstrap_form_errors form %}
    </div>

    {% if messages %}
    <ul class="messages">
      {% for mes in messages %}
      <li{% if mes.tags  %}
      class="{{ mes.tag }}"
      {% endif%}>{{ mes }}
      </li>
      {% endfor %}
    </ul>
    {% endif %}

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <label for="id_rif"> Rif </label>
    {% bootstrap_field form.rif layout="inline" %}
    <label for="id_nombre">Nombre</label>
    {% bootstrap_field form.name layout="inline" %}
    <label for="id_direccion">Dirección</label>
    {% bootstrap_field form.address layout="inline" %}
    <label for="id_regent">Regente</label>
    {% bootstrap_field form.regent layout="inline" %}
    <label for="id_institucion">Institución</label>
    {% bootstrap_field form.institucion layout="inline" %}
        {% buttons %}
        <div class="col-md-3"></div>
        <div class="col-sm-4 col-md-6 text-center">
            <br>
            <button id="id_submit" type="submit" class="btn btn-lg calculate" >
                Guardar
            </button>
            <br>
            <br>
        </div>
        <div class="col-md-3"></div>
    {% endbuttons %}
    </form>
  </div>
{% endblock %}

eHealth/templates/administrador/inbox.html
{% extends "base.html" %}
{% block content %}

<h3> Inbox </h3>
<div>
    <table id="search_result" class="display" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th>From</th>
                    <th>Subject</th>
                </tr>
            </thead>
            <tbody>
            {% for elem in result %}
                <tr>
                    <td>{{elem.sent_by}}</td>
                    <td>{{elem.subject}}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <br>
    <br>
{% endblock %}

eHealth/templates/administrador/modificar_laboratorio.html
{% extends "base.html" %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
{% block content %}
  <div id="cuerpoHeredado">
    <br>
    <h2>Modificar datos de Laboratorio</h2>
    <form action="" method=POST>
    {% csrf_token %}
    
    <div class="hidden">
        {% bootstrap_form_errors form %}
    </div>

    {% if messages %}
    <ul class="messages">
      {% for mes in messages %}
      <li{% if mes.tags  %}
      class="{{ mes.tag }}"
      {% endif%}>{{ mes }}
      </li>
      {% endfor %}
    </ul>
    {% endif %}

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    
    <label for="id_institucion">Institución</label>
    <span> {{ laboratorio.institucion }} </span>
    <label for="id_rif">Rif:</label>
    {% bootstrap_field form.rif layout="inline" %}
    <label for="id_nombre">Nombre:</label>
    {% bootstrap_field form.name layout="inline" %}
    <label for="id_direccion">Dirección: </label>
    {% bootstrap_field form.address layout="inline" %}
    <label for="id_regente">Regente:</label>
    {% bootstrap_field form.regent layout="inline" %}
        {% buttons %}
        <div class="col-md-3"></div>
        <div class="col-sm-4 col-md-6 text-center">
            <br>
            <button id="id_submit" type="submit" class="btn btn-lg calculate" >
                Guardar
            </button>
            <br>
            <br>
        </div>
        <div class="col-md-3"></div>
    {% endbuttons %}
    </form>
  </div>
{% endblock %}

eHealth/templates/administrador/modificar_usuario.html
{% extends "base.html" %}
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery=1%}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}
{% load static %}
{% block content %}
  <div id="cuerpoHeredado">
    {% if mensaje %}
      <p class="error"> <i class="fa fa-exclamation-triangle"></i>  <strong>{{ mensaje }}</strong></p>
    {% endif %}
    <h2>Modificar datos de Institucion</h2>
    <form action="" method=POST>
      {% csrf_token %}
      <div class="hidden">
          {% bootstrap_form_errors form %}
      </div>
      <label for="id_username">Nombre de usuario</label>
      {% bootstrap_field form.username layout="inline" %}
      <label for="id_first_name">Nombre</label>
      {% bootstrap_field form.first_name layout="inline" %}
      <label for="id_last_name">Apellido</label>
      {% bootstrap_field form.last_name layout="inline" %}
      <label for="id_email">Correo</label>
      {% bootstrap_field form.email layout="inline" %}
      <label for="id_rol">Rol</label>
      {% bootstrap_field form.rol layout="inline" %}
      {% buttons %}
        <div class="col-md-3"></div>
        <div class="col-sm-4 col-md-6 text-center">
            <br>
            <button id="id_submit" type="submit" class="btn btn-lg calculate">
                Guardar
            </button>
            <br>
            <br>
        </div>
        <div class="col-md-3"></div>
    {% endbuttons %}
    </form>
  </div>
{% endblock %}